apiVersion: v1
kind: Service
metadata:
  name: musicgym-front-svc
spec:
  type: ClusterIP
  selector:
    app: musicgym-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: musicgym-front-http
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  rules:
    - host: musicgym-front.201.23.17.249.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musicgym-front-svc
                port:
                  number: 80
    - host: musicgym.beloni.dev.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: musicgym-front-svc
                port:
                  number: 80
