apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: musicgym-front
  name: musicgym-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musicgym-front
  template:
    metadata:
      labels:
        app: musicgym-front
    spec:
      containers:
        - image: cbeloni/musicgym-front:arm64
          name: musicgym-front
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
